service: peanut-butter-box-api-gateway
  
configValidationMode: error

custom:
  dynamodb:
    stages:
      - dev
  tableName: 'users-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  environment:
    API_KEY_SECRET_NAME: 'okta-api-key'
    AUDIENCE: api://default
    OKTA_DOMAIN: 'https://dev-82492334.okta.com'
    OKTA_JWT_AUDIENCE: 'api://default'
    USERS_TABLE: ${self:custom.tableName}
    
functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
  authorizer:
    handler: src/index.authorizer
  getHealthcheck:
    handler: src/index.handler
    events:
      - http:
          path: /healthcheck/{proxy+}
          method: get
  deleteUser:
    handler: src/index.handler
    events:
      - http: 
          authorizer: authorizer
          method: delete
          path: /users/{proxy+}
  getUser:
    handler: src/index.handler
    events:
      - http: 
          authorizer: authorizer
          method: get
          path: /users/{proxy+}
        
  postUser:
    handler: src/index.handler
    events:
      - http:
          method: post
          path: /users
  putUser:
    handler: src/index.handler
    events:
      - http:
          authorizer: authorizer
          method: put
          path: /users

plugins:
  - serverless-finch
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}